worker_processes 1;
error_log /dev/stderr;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;

    server {
        listen $PORT;
        server_name _;
        root /app;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
